{% set name = "xarrayMannKendall" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarrayMannKendall-{{ version }}.tar.gz
  sha256: 9a4e1f7144021c2235ac1d2f828d7b68a57b8bfb555c7ed3f1bb8314bd28cd8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - xarray
    - dask

test:
  imports:
    - xarrayMannKendall
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/josuemtzmo/xarrayMannKendall
  summary: Mann-Kendall statistical test to assess if a monotonic upward or downward trend exists over time.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - josuemtzmo
